apiVersion: v1
kind: Secret
metadata:
  name: notifier-secrets
  labels:
    app.kubernetes.io/name: notifier
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  slackWebhook: {{ .Values.env.SLACK_WEBHOOK | quote }}
  testSlackWebhook: {{ .Values.env.TEST_SLACK_WEBHOOK | quote }}
