apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    app: notifier
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: app
      port: {{ .Values.service.port | default 5000 }}
      targetPort: {{ .Values.service.targetPort | default 5000 }}
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort | default 8000 }}
      targetPort: {{ .Values.service.metricsTargetPort | default 8000 }}
      protocol: TCP
  selector:
    app: notifier
    release: {{ .Release.Name }}
