apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  CHECK_INTERVAL: "{{ .Values.config.checkInterval }}"
  TEST_FLOW: "{{ .Values.config.testFlow }}"
  LOG_LEVEL: "{{ .Values.config.logLevel }}"